os: linux
dist: focal
arch: amd64

language: go
go:
  - 1.15.x
  # - master

script:
  - go build ./cmd/server/main.go

jobs:
  include:
    - stage: deploy
      if: branch = main
      install:
        - curl -LJO https://github.com/intuit/auto/releases/download/v10.16.6/auto-linux.gz
        - gunzip auto-linux.gz
        - sudo mv auto-linux /usr/local/bin/auto
        - sudo chmod a+x /usr/local/bin/auto
      script: skip
      before_deploy: ./ci/update_version.sh
      deploy:
        - provider: script
          script: echo $TRAVIS_COMMIT_MESSAGE
          cleanup: true
          on:
            branch: main
