os: linux
arch: amd64

language: go
go:
  - 1.15.x
  - master

script:
  - go build ./cmd/server/main.go

jobs:
  include:
    - stage: release
      if: branch = main AND type = push
      install:
        - curl -LJO https://github.com/intuit/auto/releases/download/v10.16.6/auto-linux.gz
        - gunzip auto-linux.gz
        - mv auto-linux $GOPATH/bin/auto
        - chmod +x $GOPATH/bin/auto
      go: 1.15.x
      script: skip
      deploy:
        - provider: script
          script: git checkout main && ./ci/update_version.sh && auto shipit    
          cleanup: true
          on:
            branch: main
